#!/usr/bin/env python3
"""
Automotive MISRA Deviation Permit Generator
Compliant with MISRA Compliance:2020 & ISO 26262:2018
Part of AutoSafe-Review (Tata TechPulse CS4)
Student: Pranav Ravindra Harad | PRN: 123B1F028 | PCCOE, Pune
"""

import datetime
from typing import Dict, Any

def generate_deviation_permit(finding: Dict[str, Any], 
                              engineer_name: str, 
                              prn: str, 
                              technical_justification: str, 
                              mitigation_steps: str) -> str:
    """
    Generates a formal MISRA Compliance:2020 Deviation Record for engineering disposition.
    """
    dev_id = f"DEV-{datetime.date.today().year}-{abs(hash(finding.get('finding_id', '') + technical_justification)) % 10000:04d}"
    now_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    permit = f"""================================================================================
       AUTOMOTIVE ENGINEERING MISRA DEVIATION RECORD (PERMIT)
================================================================================
Permit ID:              {dev_id}
Date & Timestamp:       {now_str}
Project / ECU:          High-Voltage Traction Inverter / BMS Controller
Software Component:     {finding.get('file', 'source.c')}
Exact Line Number:      Line {finding.get('line', 'N/A')}

--------------------------------------------------------------------------------
1. RULE & STANDARD VIOLATION DETAILS
--------------------------------------------------------------------------------
Standard:               {finding.get('standard', 'MISRA C:2012')}
Rule ID:                {finding.get('rule_id', 'N/A')}
Classification:         {finding.get('severity', 'Required')}
CWE Reference:          {finding.get('cwe', 'N/A')}
Target ASIL Category:   ASIL-B / ASIL-D Functional Safety

Offending Code Snippet:
    {finding.get('code_snippet', '').strip()}

--------------------------------------------------------------------------------
2. TECHNICAL DEVIATION RATIONALE
--------------------------------------------------------------------------------
Engineering Justification:
    {technical_justification.strip()}

Functional Safety Impact Assessment (ISO 26262):
    {finding.get('safety_impact', 'Risk assessed and managed by hardware watchdog.')}

--------------------------------------------------------------------------------
3. RISK MITIGATION & COMPENSATING CONTROLS
--------------------------------------------------------------------------------
Mitigation Measures Enforced:
    {mitigation_steps.strip()}

Verification Evidence Required:
    - Unit testing branch coverage (MC/DC >= 90%)
    - Static code analysis suppression comment attached to line
    - Hardware-in-the-Loop (HIL) fault-injection testing

--------------------------------------------------------------------------------
4. SIGN-OFF & HUMAN OVERSIGHT APPROVAL
--------------------------------------------------------------------------------
Requesting Engineer:    {engineer_name} (PRN: {prn})
Role:                   Embedded Software Developer
Approval Status:        PROVISIONALLY APPROVED (Pending Functional Safety Lead)
Safety Manager Sign-off: _______________________________ Date: _______________

================================================================================
Generated by AutoSafe-Review Air-Gapped Assistant (Tata TechPulse FY-26)
================================================================================
"""
    return permit
