#!/usr/bin/env python3
"""
Structured Audit Report Exporter (CSV, JSON, Markdown)
Part of AutoSafe-Review (Tata TechPulse CS4)
Student: Pranav Ravindra Harad | PRN: 123B1F028 | PCCOE, Pune
"""

import csv
import json
import io
from typing import List, Dict, Any

def export_findings_to_csv(findings: List[Dict[str, Any]]) -> str:
    """Exports findings to CSV string."""
    output = io.StringIO()
    fieldnames = [
        "finding_id", "file", "line", "rule_id", "standard", 
        "severity", "cwe", "root_cause", "safety_impact", "confidence"
    ]
    writer = csv.DictWriter(output, fieldnames=fieldnames, extrasaction='ignore')
    writer.writeheader()
    for f in findings:
        writer.writerow(f)
    return output.getvalue()

def export_findings_to_markdown(summary: Dict[str, Any], findings: List[Dict[str, Any]]) -> str:
    """Generates a clean Markdown review report."""
    md = [
        "# Automotive Code Review & Compliance Audit Report",
        "**Generated by AutoSafe-Review (Tata Technologies TechPulse CS4)**",
        f"**File Analyzed:** `{summary.get('file', 'Unknown')}`  ",
        f"**Total Findings:** {len(findings)} | **Critical/Mandatory:** {summary.get('summary', {}).get('critical_and_mandatory', 0)} | **Required:** {summary.get('summary', {}).get('required_and_high', 0)}\n",
        "---",
        "## Detailed Findings\n"
    ]

    for idx, f in enumerate(findings, start=1):
        md.append(f"### Finding {idx}: [{f.get('rule_id')}] - {f.get('standard')}")
        md.append(f"- **Location:** `{f.get('file')}:{f.get('line')}`")
        md.append(f"- **Severity:** `{f.get('severity')}` | **CWE:** `{f.get('cwe')}`")
        md.append(f"- **Root Cause:** {f.get('root_cause')}")
        md.append(f"- **Safety Impact:** {f.get('safety_impact')}")
        md.append(f"- **Compliant Fix Recommendation:**\n```c\n{f.get('suggested_fix')}\n```\n")

    return "\n".join(md)
